In [48]:
import numpy as np
import pandas as pd

# Series form LIST

In [ ]:
# series from lists

country = ["Nepal", "India", "Bhutan", "USA", "Australia"]
pd.Series(country)

0        Nepal
1        India
2       Bhutan
3          USA
4    Australia
dtype: object

In [ ]:
# integers

runs = [10,32,10,101,65]
pd.Series(runs)

0     10
1     32
2     10
3    101
4     65
dtype: int64

In [ ]:
# custom index

marks = [66, 70,64,68,72]
subs = ["nepali", "social", "english", "account", "maths"]

pd.Series(marks, index=subs)

nepali     66
social     70
english    64
account    68
maths      72
dtype: int64

In [ ]:
#  setting a name

marks = [66, 70,64,68,72]
subs = ["nepali", "social", "english", "account", "maths"]

my_marks = pd.Series(marks, index=subs, name = "jiban mark's")
my_marks

nepali     66
social     70
english    64
account    68
maths      72
Name: jiban mark's, dtype: int64

# Series from Dictionary

In [ ]:
marks = {
    "english" : 64,
    "nepali" : 66,
    "social" : 70,
    "maths" : 72,
    "computer" : 47,
    "account" : 70
}

marks_series = pd.Series(marks, name = "Jiban Marks")
print(marks_series)

english     64
nepali      66
social      70
maths       72
computer    47
account     70
Name: Jiban Marks, dtype: int64

# Series Attributes

In [ ]:
#  size

marks_series.size

6

In [ ]:
# dtype

marks_series.dtype

dtype('int64')

In [ ]:
# name
marks_series.name

'Jiban Marks'

In [ ]:
# is_unique
marks_series.is_unique

False

In [ ]:
# index

marks_series.index

Index(['english', 'nepali', 'social', 'maths', 'computer', 'account'], dtype='object')

In [ ]:
# values

marks_series.values

array([64, 66, 70, 72, 47, 70])

# Series using read_csv

In [49]:
# with one col (col -> column)

subs_ser = pd.read_csv('/content/subs.csv').squeeze()
print(subs_ser)

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [50]:
#  with 2 col(column)

virat_ser = pd.read_csv("/content/kohli_ipl.csv", index_col='match_no').squeeze()

print(virat_ser)

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [57]:
movies = pd.read_csv("/content/bollywood.csv", index_col = "movie").squeeze()


print(movies)

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

# Series Methods

In [52]:
# head and tail
# ---> head for first 5 default
virat_ser.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [53]:
#  tail for last 5 default
virat_ser.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [56]:
# sample ---> randomly one set default but can add also how many you want

virat_ser.sample()

match_no
129    54
Name: runs, dtype: int64

In [58]:
# value_counts

movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [59]:
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64